[2024-04-20T14:06:36.216+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing_pound.get_data manual__2024-04-20T14:01:23.073825+00:00 [queued]>
[2024-04-20T14:06:36.232+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing_pound.get_data manual__2024-04-20T14:01:23.073825+00:00 [queued]>
[2024-04-20T14:06:36.233+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-20T14:06:36.259+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_data> on 2024-04-20 14:01:23.073825+00:00
[2024-04-20T14:06:36.267+0000] {standard_task_runner.py:60} INFO - Started process 1146 to run task
[2024-04-20T14:06:36.274+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing_pound', 'get_data', 'manual__2024-04-20T14:01:23.073825+00:00', '--job-id', '872', '--raw', '--subdir', 'DAGS_FOLDER/stage/currency_pound.py', '--cfg-path', '/tmp/tmp1stpscjq']
[2024-04-20T14:06:36.277+0000] {standard_task_runner.py:88} INFO - Job 872: Subtask get_data
[2024-04-20T14:06:36.367+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing_pound.get_data manual__2024-04-20T14:01:23.073825+00:00 [running]> on host 31aa6d9ea6ff
[2024-04-20T14:06:36.446+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-04-20T14:06:36.515+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing_pound' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-20T14:01:23.073825+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-20T14:01:23.073825+00:00'
[2024-04-20T14:06:36.985+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stage/currency_pound.py", line 11, in get_data
    data = client.historical(f'{year}-{int(month):02d}-{int(day):02d}', base_currency='GBP')
  File "/home/airflow/.local/lib/python3.8/site-packages/freecurrencyapi/client.py", line 32, in historical
    return self._request('/historical', params={
  File "/home/airflow/.local/lib/python3.8/site-packages/everapi/client.py", line 74, in _request
    raise everapi.exceptions.ApiError(
everapi.exceptions.ApiError: ('API returned errors:', {'date': ['The date must be a date before or equal to 2024-04-19T14:06:37Z.']})
[2024-04-20T14:06:37.035+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=currency_parsing_pound, task_id=get_data, execution_date=20240420T140123, start_date=20240420T140636, end_date=20240420T140637
[2024-04-20T14:06:37.081+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 872 for task get_data (('API returned errors:', {'date': ['The date must be a date before or equal to 2024-04-19T14:06:37Z.']}); 1146)
[2024-04-20T14:06:37.132+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-20T14:06:37.214+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
