[2024-04-20T14:17:17.814+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing_pound.get_data manual__2024-04-20T14:01:23.073825+00:00 [queued]>
[2024-04-20T14:17:17.829+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing_pound.get_data manual__2024-04-20T14:01:23.073825+00:00 [queued]>
[2024-04-20T14:17:17.830+0000] {taskinstance.py:2193} INFO - Starting attempt 8 of 9
[2024-04-20T14:17:17.851+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_data> on 2024-04-20 14:01:23.073825+00:00
[2024-04-20T14:17:17.858+0000] {standard_task_runner.py:60} INFO - Started process 1307 to run task
[2024-04-20T14:17:17.863+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing_pound', 'get_data', 'manual__2024-04-20T14:01:23.073825+00:00', '--job-id', '877', '--raw', '--subdir', 'DAGS_FOLDER/stage/currency_pound.py', '--cfg-path', '/tmp/tmp7x8e6_e9']
[2024-04-20T14:17:17.866+0000] {standard_task_runner.py:88} INFO - Job 877: Subtask get_data
[2024-04-20T14:17:17.944+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing_pound.get_data manual__2024-04-20T14:01:23.073825+00:00 [running]> on host 31aa6d9ea6ff
[2024-04-20T14:17:18.020+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-04-20T14:17:18.075+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing_pound' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-20T14:01:23.073825+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-20T14:01:23.073825+00:00'
[2024-04-20T14:17:18.086+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stage/currency_pound.py", line 10, in get_data
    execution_date = datetime.strptime(execution_date, '%Y-%m-%d')
  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.8/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains:  14:01:23.073825+00:00
[2024-04-20T14:17:18.104+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=currency_parsing_pound, task_id=get_data, execution_date=20240420T140123, start_date=20240420T141717, end_date=20240420T141718
[2024-04-20T14:17:18.122+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 877 for task get_data (unconverted data remains:  14:01:23.073825+00:00; 1307)
[2024-04-20T14:17:18.157+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-20T14:17:18.260+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
