[2024-05-01T15:04:39.611+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing.fetch_data_kzt scheduled__2024-04-30T00:00:00+00:00 [queued]>
[2024-05-01T15:04:39.635+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing.fetch_data_kzt scheduled__2024-04-30T00:00:00+00:00 [queued]>
[2024-05-01T15:04:39.636+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-05-01T15:04:39.669+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): fetch_data_kzt> on 2024-04-30 00:00:00+00:00
[2024-05-01T15:04:39.677+0000] {standard_task_runner.py:60} INFO - Started process 882 to run task
[2024-05-01T15:04:39.697+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing', 'fetch_data_kzt', 'scheduled__2024-04-30T00:00:00+00:00', '--job-id', '2603', '--raw', '--subdir', 'DAGS_FOLDER/stage/currency_parsing.py', '--cfg-path', '/tmp/tmpg7o3drij']
[2024-05-01T15:04:39.704+0000] {standard_task_runner.py:88} INFO - Job 2603: Subtask fetch_data_kzt
[2024-05-01T15:04:40.063+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing.fetch_data_kzt scheduled__2024-04-30T00:00:00+00:00 [running]> on host 84be22a86186
[2024-05-01T15:04:43.934+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing' AIRFLOW_CTX_TASK_ID='fetch_data_kzt' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-30T00:00:00+00:00'
[2024-05-01T15:04:44.048+0000] {base.py:83} INFO - Using connection ID 'dwh' for task execution.
[2024-05-01T15:04:44.067+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stage/currency_parsing.py", line 106, in fetch_data_kzt
    dwh_hook.insert_rows(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 565, in insert_rows
    cur.execute(sql, values)
psycopg2.errors.UndefinedTable: relation "stage.currency_parsing_kzt" does not exist
LINE 1: INSERT INTO stage.currency_parsing_kzt (currency, title, rat...
                    ^

[2024-05-01T15:04:44.092+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=currency_parsing, task_id=fetch_data_kzt, execution_date=20240430T000000, start_date=20240501T150439, end_date=20240501T150444
[2024-05-01T15:04:44.207+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2603 for task fetch_data_kzt (relation "stage.currency_parsing_kzt" does not exist
LINE 1: INSERT INTO stage.currency_parsing_kzt (currency, title, rat...
                    ^
; 882)
[2024-05-01T15:04:44.244+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-01T15:04:44.269+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-05-01T15:04:44.309+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T10:55:16.505+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing.fetch_data_kzt scheduled__2024-04-30T00:00:00+00:00 [queued]>
[2024-05-05T10:55:17.081+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing.fetch_data_kzt scheduled__2024-04-30T00:00:00+00:00 [queued]>
[2024-05-05T10:55:17.201+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-05-05T10:55:17.827+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): fetch_data_kzt> on 2024-04-30 00:00:00+00:00
[2024-05-05T10:55:17.936+0000] {standard_task_runner.py:60} INFO - Started process 762 to run task
[2024-05-05T10:55:18.026+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing', 'fetch_data_kzt', 'scheduled__2024-04-30T00:00:00+00:00', '--job-id', '2700', '--raw', '--subdir', 'DAGS_FOLDER/currency_dag/currency_parsing.py', '--cfg-path', '/tmp/tmpnqupj3nl']
[2024-05-05T10:55:18.194+0000] {standard_task_runner.py:88} INFO - Job 2700: Subtask fetch_data_kzt
[2024-05-05T10:55:18.769+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing.fetch_data_kzt scheduled__2024-04-30T00:00:00+00:00 [running]> on host 71addd39200f
[2024-05-05T10:55:21.171+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing' AIRFLOW_CTX_TASK_ID='fetch_data_kzt' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-30T00:00:00+00:00'
[2024-05-05T10:55:21.485+0000] {base.py:83} INFO - Using connection ID 'dwh' for task execution.
[2024-05-05T10:55:21.698+0000] {sql.py:572} INFO - Done loading. Loaded a total of 39 rows into stage.currency_kzt
[2024-05-05T10:55:21.700+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-05-05T10:55:21.909+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=currency_parsing, task_id=fetch_data_kzt, execution_date=20240430T000000, start_date=20240505T105516, end_date=20240505T105521
[2024-05-05T10:55:22.038+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-05T10:55:22.730+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
