[2024-04-14T09:00:05.028+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kolesa_dag_2.save_data manual__2024-04-14T08:54:51.288059+00:00 [queued]>
[2024-04-14T09:00:05.043+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kolesa_dag_2.save_data manual__2024-04-14T08:54:51.288059+00:00 [queued]>
[2024-04-14T09:00:05.044+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-14T09:00:05.065+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): save_data> on 2024-04-14 08:54:51.288059+00:00
[2024-04-14T09:00:05.071+0000] {standard_task_runner.py:60} INFO - Started process 1518 to run task
[2024-04-14T09:00:05.077+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kolesa_dag_2', 'save_data', 'manual__2024-04-14T08:54:51.288059+00:00', '--job-id', '477', '--raw', '--subdir', 'DAGS_FOLDER/kolesa_from_csv.py', '--cfg-path', '/tmp/tmpb_j7iwk1']
[2024-04-14T09:00:05.081+0000] {standard_task_runner.py:88} INFO - Job 477: Subtask save_data
[2024-04-14T09:00:05.154+0000] {task_command.py:423} INFO - Running <TaskInstance: kolesa_dag_2.save_data manual__2024-04-14T08:54:51.288059+00:00 [running]> on host e8a1e0443283
[2024-04-14T09:00:05.525+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kolesa_dag_2' AIRFLOW_CTX_TASK_ID='save_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T08:54:51.288059+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T08:54:51.288059+00:00'
[2024-04-14T09:00:05.595+0000] {base.py:83} INFO - Using connection ID 'dwh' for task execution.
[2024-04-14T09:00:05.842+0000] {sql.py:572} INFO - Done loading. Loaded a total of 416 rows into kolesa_parsing
[2024-04-14T09:00:05.844+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-14T09:00:05.860+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=kolesa_dag_2, task_id=save_data, execution_date=20240414T085451, start_date=20240414T090005, end_date=20240414T090005
[2024-04-14T09:00:05.932+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-14T09:00:05.963+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
