[2024-04-21T10:53:51.291+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing.get_data_rub scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-21T10:53:52.007+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing.get_data_rub scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-21T10:53:52.217+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-21T10:53:54.351+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_data_rub> on 2024-01-16 00:00:00+00:00
[2024-04-21T10:53:55.137+0000] {standard_task_runner.py:60} INFO - Started process 1249 to run task
[2024-04-21T10:53:55.065+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing', 'get_data_rub', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '1407', '--raw', '--subdir', 'DAGS_FOLDER/stage/currency_parsing.py', '--cfg-path', '/tmp/tmpfji2goww']
[2024-04-21T10:53:55.686+0000] {standard_task_runner.py:88} INFO - Job 1407: Subtask get_data_rub
[2024-04-21T10:53:57.178+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing.get_data_rub scheduled__2024-01-16T00:00:00+00:00 [running]> on host e671688b1343
[2024-04-21T10:53:59.588+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-04-21T10:54:01.896+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing' AIRFLOW_CTX_TASK_ID='get_data_rub' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T00:00:00+00:00'
[2024-04-21T10:54:15.072+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stage/currency_parsing.py", line 37, in get_data_rub
    currencies_date = datetime.strptime(currency_data['Date'][:10], '%Y-%m-%d')
KeyError: 'Date'
[2024-04-21T10:54:15.196+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=currency_parsing, task_id=get_data_rub, execution_date=20240116T000000, start_date=20240421T105351, end_date=20240421T105415
[2024-04-21T10:54:15.383+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1407 for task get_data_rub ('Date'; 1249)
[2024-04-21T10:54:15.533+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-21T10:54:16.099+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
