[2024-04-21T10:45:50.941+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing.get_data_rub scheduled__2024-01-07T00:00:00+00:00 [queued]>
[2024-04-21T10:45:51.161+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing.get_data_rub scheduled__2024-01-07T00:00:00+00:00 [queued]>
[2024-04-21T10:45:51.164+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-21T10:45:51.410+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_data_rub> on 2024-01-07 00:00:00+00:00
[2024-04-21T10:45:51.452+0000] {standard_task_runner.py:60} INFO - Started process 470 to run task
[2024-04-21T10:45:51.475+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing', 'get_data_rub', 'scheduled__2024-01-07T00:00:00+00:00', '--job-id', '1064', '--raw', '--subdir', 'DAGS_FOLDER/stage/currency_parsing.py', '--cfg-path', '/tmp/tmpag98y3eq']
[2024-04-21T10:45:51.525+0000] {standard_task_runner.py:88} INFO - Job 1064: Subtask get_data_rub
[2024-04-21T10:45:51.985+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing.get_data_rub scheduled__2024-01-07T00:00:00+00:00 [running]> on host e671688b1343
[2024-04-21T10:45:52.711+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-04-21T10:45:53.153+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing' AIRFLOW_CTX_TASK_ID='get_data_rub' AIRFLOW_CTX_EXECUTION_DATE='2024-01-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-07T00:00:00+00:00'
[2024-04-21T10:46:05.373+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stage/currency_parsing.py", line 37, in get_data_rub
    currencies_date = datetime.strptime(currency_data['Date'][:10], '%Y-%m-%d')
KeyError: 'Date'
[2024-04-21T10:46:05.523+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=currency_parsing, task_id=get_data_rub, execution_date=20240107T000000, start_date=20240421T104550, end_date=20240421T104605
[2024-04-21T10:46:05.793+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1064 for task get_data_rub ('Date'; 470)
[2024-04-21T10:46:05.990+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-21T10:46:06.405+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
