[2024-04-27T12:31:11.186+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing.populate_intermediate_schema scheduled__2024-04-06T00:00:00+00:00 [queued]>
[2024-04-27T12:31:11.476+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing.populate_intermediate_schema scheduled__2024-04-06T00:00:00+00:00 [queued]>
[2024-04-27T12:31:11.487+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-27T12:31:12.851+0000] {taskinstance.py:2214} INFO - Executing <Task(PostgresOperator): populate_intermediate_schema> on 2024-04-06 00:00:00+00:00
[2024-04-27T12:31:13.105+0000] {standard_task_runner.py:60} INFO - Started process 2527 to run task
[2024-04-27T12:31:13.212+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing', 'populate_intermediate_schema', 'scheduled__2024-04-06T00:00:00+00:00', '--job-id', '2548', '--raw', '--subdir', 'DAGS_FOLDER/stage/currency_parsing.py', '--cfg-path', '/tmp/tmp0crpx8y9']
[2024-04-27T12:31:13.344+0000] {standard_task_runner.py:88} INFO - Job 2548: Subtask populate_intermediate_schema
[2024-04-27T12:31:14.282+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing.populate_intermediate_schema scheduled__2024-04-06T00:00:00+00:00 [running]> on host 65a8688265d1
[2024-04-27T12:31:14.923+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing' AIRFLOW_CTX_TASK_ID='populate_intermediate_schema' AIRFLOW_CTX_EXECUTION_DATE='2024-04-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-06T00:00:00+00:00'
[2024-04-27T12:31:15.015+0000] {sql.py:276} INFO - Executing: CREATE TABLE intermediate.currency as
select f1.currency,
       f1.title,
       f1.rate as rate_kzt,
       f2.value as rate_rub,
       round(1/f3.rate::numeric, 3) as rate_usd,
       round(1/f4.rate::numeric, 3) as rate_pound,
       f1.date
from stage.currency_parsing_kzt f1
    left join stage.currency_parsing_rub f2
        on f1.date = f2.date and f1.title = f2.charcode
    left join stage.currency_parsing_usd f3
        on f1.date = f3.date and f1.title = f3.title
    left join stage.currency_parsing_pound f4
        on f1.date = f4.date and f1.title = f4.title;
[2024-04-27T12:31:15.467+0000] {base.py:83} INFO - Using connection ID 'dwh' for task execution.
[2024-04-27T12:31:15.559+0000] {base.py:83} INFO - Using connection ID 'dwh' for task execution.
[2024-04-27T12:31:15.621+0000] {sql.py:457} INFO - Running statement: CREATE TABLE intermediate.currency as
select f1.currency,
       f1.title,
       f1.rate as rate_kzt,
       f2.value as rate_rub,
       round(1/f3.rate::numeric, 3) as rate_usd,
       round(1/f4.rate::numeric, 3) as rate_pound,
       f1.date
from stage.currency_parsing_kzt f1
    left join stage.currency_parsing_rub f2
        on f1.date = f2.date and f1.title = f2.charcode
    left join stage.currency_parsing_usd f3
        on f1.date = f3.date and f1.title = f3.title
    left join stage.currency_parsing_pound f4
        on f1.date = f4.date and f1.title = f4.title;, parameters: None
[2024-04-27T12:31:15.638+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateTable: relation "currency" already exists

[2024-04-27T12:31:15.716+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=currency_parsing, task_id=populate_intermediate_schema, execution_date=20240406T000000, start_date=20240427T123111, end_date=20240427T123115
[2024-04-27T12:31:16.362+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2548 for task populate_intermediate_schema (relation "currency" already exists
; 2527)
[2024-04-27T12:31:16.481+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-27T12:31:16.783+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
