[2024-04-13T12:13:46.886+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing.get_data scheduled__2009-02-24T00:00:00+00:00 [queued]>
[2024-04-13T12:13:46.931+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing.get_data scheduled__2009-02-24T00:00:00+00:00 [queued]>
[2024-04-13T12:13:46.933+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-13T12:13:46.975+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_data> on 2009-02-24 00:00:00+00:00
[2024-04-13T12:13:46.990+0000] {standard_task_runner.py:60} INFO - Started process 97 to run task
[2024-04-13T12:13:47.008+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing', 'get_data', 'scheduled__2009-02-24T00:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/currency_parsing.py', '--cfg-path', '/tmp/tmp0782f_sj']
[2024-04-13T12:13:47.016+0000] {standard_task_runner.py:88} INFO - Job 106: Subtask get_data
[2024-04-13T12:13:47.317+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing.get_data scheduled__2009-02-24T00:00:00+00:00 [running]> on host e8a1e0443283
[2024-04-13T12:13:47.521+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-04-13T12:13:47.801+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2009-02-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2009-02-24T00:00:00+00:00'
[2024-04-13T12:13:47.841+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/currency_parsing.py", line 11, in _get_data
    date_obj = datetime.strptime(f"{year}-{month}-{day}", "%Y-%m-d%").date()
  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.8/_strptime.py", line 345, in _strptime
    raise ValueError("stray %% in format '%s'" % format) from None
ValueError: stray % in format '%Y-%m-d%'
[2024-04-13T12:13:47.876+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=currency_parsing, task_id=get_data, execution_date=20090224T000000, start_date=20240413T121346, end_date=20240413T121347
[2024-04-13T12:13:47.958+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 106 for task get_data (stray % in format '%Y-%m-d%'; 97)
[2024-04-13T12:13:48.071+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-13T12:13:48.364+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
