[2024-05-03T12:45:39.759+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:45:39.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:45:39.772+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:45:39.771+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:45:39.857+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:45:39.856+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:45:39.871+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:45:39.950+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:45:39.949+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:45:40.007+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:45:40.007+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:45:40.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 0.313 seconds
[2024-05-03T12:46:22.535+0000] {processor.py:161} INFO - Started process (PID=110) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:46:22.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:46:22.566+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:46:22.566+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:46:23.166+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:46:23.158+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:46:23.237+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:46:23.511+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:46:23.510+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:46:23.789+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:46:23.789+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:46:24.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 1.588 seconds
[2024-05-03T12:46:54.917+0000] {processor.py:161} INFO - Started process (PID=121) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:46:54.922+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:46:54.927+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:46:54.927+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:46:55.016+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:46:55.015+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:46:55.035+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:46:55.182+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:46:55.182+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:46:55.312+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:46:55.311+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:46:55.401+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 0.489 seconds
[2024-05-03T12:47:25.875+0000] {processor.py:161} INFO - Started process (PID=132) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:47:25.877+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:47:25.880+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:47:25.879+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:47:25.920+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:47:25.919+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:47:25.928+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:47:25.965+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:47:25.965+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:47:26.003+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:47:26.003+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:47:26.064+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 0.196 seconds
[2024-05-03T12:47:56.396+0000] {processor.py:161} INFO - Started process (PID=144) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:47:56.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:47:56.401+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:47:56.401+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:47:56.443+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:47:56.442+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:47:56.449+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:47:56.492+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:47:56.491+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:47:56.529+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:47:56.529+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:47:56.562+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 0.174 seconds
[2024-05-03T12:48:27.122+0000] {processor.py:161} INFO - Started process (PID=154) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:48:27.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:48:27.161+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:48:27.160+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:48:27.495+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:48:27.493+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:48:27.511+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:48:27.694+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:48:27.694+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:48:28.003+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:48:27.989+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:48:28.219+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 1.138 seconds
[2024-05-03T12:48:58.982+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:48:58.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:48:58.987+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:48:58.986+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:48:59.035+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:48:59.033+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:48:59.042+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:48:59.081+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:48:59.080+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:48:59.122+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:48:59.121+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:48:59.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 0.179 seconds
[2024-05-03T12:49:29.250+0000] {processor.py:161} INFO - Started process (PID=175) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:49:29.252+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:49:29.254+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:49:29.254+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:49:29.290+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:49:29.289+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:49:29.297+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:49:29.331+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:49:29.330+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:49:29.361+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:49:29.361+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:49:29.390+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 0.145 seconds
[2024-05-03T12:49:59.465+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:49:59.467+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:49:59.471+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:49:59.471+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:49:59.520+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:49:59.518+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:49:59.525+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:49:59.570+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:49:59.570+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:49:59.609+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:49:59.608+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:49:59.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 0.181 seconds
[2024-05-03T12:50:29.736+0000] {processor.py:161} INFO - Started process (PID=197) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:50:29.738+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:50:29.741+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:50:29.740+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:50:29.794+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:50:29.793+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:50:29.802+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:50:29.851+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:50:29.851+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:50:29.897+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:50:29.897+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:50:29.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 0.206 seconds
[2024-05-03T12:51:00.026+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:51:00.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:51:00.055+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:51:00.054+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:51:00.113+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:51:00.111+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:51:00.121+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:51:00.183+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:51:00.183+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:51:00.237+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:51:00.233+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:51:00.275+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 0.265 seconds
[2024-05-03T12:51:30.985+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:51:31.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:51:31.026+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:51:31.025+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:51:31.460+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:51:31.457+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:51:31.478+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:51:31.655+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:51:31.654+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:51:31.916+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:51:31.916+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:51:34.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 3.583 seconds
[2024-05-03T12:52:05.162+0000] {processor.py:161} INFO - Started process (PID=230) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:52:05.165+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:52:05.182+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:52:05.174+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:52:05.550+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:52:05.548+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:52:05.628+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:52:06.054+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:52:06.054+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:52:06.248+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:52:06.247+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:52:06.309+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 1.163 seconds
[2024-05-03T12:52:36.561+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:52:36.563+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:52:36.568+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:52:36.567+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:52:36.798+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:52:36.796+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:52:36.821+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:52:37.000+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:52:37.000+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:52:37.096+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:52:37.095+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:52:39.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 2.567 seconds
[2024-05-03T12:53:09.888+0000] {processor.py:161} INFO - Started process (PID=253) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:53:09.902+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:53:09.922+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:53:09.917+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:53:10.353+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:53:10.349+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:53:10.386+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:53:10.814+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:53:10.813+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:53:10.990+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:53:10.989+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:53:11.146+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 1.443 seconds
[2024-05-03T12:53:41.756+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:53:41.769+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:53:41.792+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:53:41.791+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:53:42.023+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:53:42.015+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:53:42.092+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:53:42.324+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:53:42.323+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:53:42.836+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:53:42.835+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:53:43.112+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 1.444 seconds
[2024-05-03T12:54:14.319+0000] {processor.py:161} INFO - Started process (PID=275) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:54:14.343+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:54:14.385+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:54:14.384+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:54:14.682+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:54:14.679+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:54:14.740+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:54:14.968+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:54:14.967+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:54:15.197+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:54:15.196+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:54:15.576+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 1.300 seconds
[2024-05-03T12:54:46.352+0000] {processor.py:161} INFO - Started process (PID=286) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:54:46.358+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:54:46.462+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:54:46.460+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:54:46.689+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:54:46.687+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:54:46.781+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:54:47.228+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:54:47.227+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:54:47.346+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:54:47.345+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:54:47.516+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 1.265 seconds
[2024-05-03T12:55:17.867+0000] {processor.py:161} INFO - Started process (PID=297) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:55:17.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:55:17.882+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:55:17.881+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:55:19.410+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:55:19.402+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:55:19.435+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:55:23.753+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:55:23.752+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:55:24.848+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:55:24.847+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:55:27.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 9.849 seconds
[2024-05-03T12:56:04.916+0000] {processor.py:161} INFO - Started process (PID=314) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:56:04.965+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:56:05.121+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:56:05.116+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:56:06.581+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:56:06.579+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:56:06.918+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:56:07.453+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:56:07.449+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:56:08.576+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:56:08.557+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:56:11.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 6.574 seconds
[2024-05-03T12:56:43.926+0000] {processor.py:161} INFO - Started process (PID=324) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:56:44.017+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:56:44.379+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:56:44.378+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:56:45.476+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:56:45.472+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:56:45.645+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:56:47.540+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:56:47.515+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:56:48.972+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:56:48.972+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:56:50.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 6.220 seconds
[2024-05-03T12:57:25.628+0000] {processor.py:161} INFO - Started process (PID=335) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:57:25.664+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:57:25.681+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:57:25.680+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:57:27.644+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:57:27.578+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:57:27.821+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:57:31.556+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:57:31.477+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:57:35.646+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:57:35.646+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:57:37.914+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 12.361 seconds
[2024-05-03T12:58:09.347+0000] {processor.py:161} INFO - Started process (PID=352) to work on /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:58:09.373+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test/simple_insert_movies.py for tasks to queue
[2024-05-03T12:58:09.394+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:58:09.393+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:58:09.794+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:58:09.791+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/create_movies.sql
[2024-05-03T12:58:09.845+0000] {processor.py:840} INFO - DAG(s) 'movie_night' retrieved from /opt/airflow/dags/test/simple_insert_movies.py
[2024-05-03T12:58:10.520+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:58:10.520+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-05-03T12:58:11.144+0000] {logging_mixin.py:188} INFO - [2024-05-03T12:58:11.143+0000] {dag.py:3834} INFO - Setting next_dagrun for movie_night to None, run_after=None
[2024-05-03T12:58:11.471+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test/simple_insert_movies.py took 2.150 seconds
